using Blue_Jays_Manager.Models.DataAccessLayer;
using Blue_Jays_Manager.Models.DataModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Blue_Jays_Manager
{
    public partial class Coaches : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                DataRetrieval retrieve = new DataRetrieval();
                List<CoachRoster> roster = retrieve.SelectAllCoaches();
                if (Session["login"].ToString() == "loggedIn")
                {
                    CoachRosterGridView.AutoGenerateEditButton = true;
                    CoachRosterGridView.AutoGenerateDeleteButton = true;
                }

                if (Cache["CoachRoster"] == null)
                {
                    Cache.Insert("CoachRoster", roster);
                }
            }

            CoachRosterGridView.DataSource = (List<CoachRoster>)Cache["CoachRoster"];
            CoachRosterGridView.DataBind();

            if (Session["login"].ToString() != "loggedIn")
            {
                _hideColumn(3);
                _hideColumn(4);
            }
        }

        private void _hideColumn(int v)
        {
            CoachRosterGridView.HeaderRow.Cells[v].Visible = false;

            for (int i = 0; i < CoachRosterGridView.Rows.Count; i++)
            {
                CoachRosterGridView.Rows[i].Cells[v].Visible = false;
            }
            CoachRosterGridView.FooterRow.Cells[v].Visible = false;
        }

        protected void EnableUser(object sender, GridViewCommandEventArgs e)
        {
            string name = e.CommandArgument.ToString();
            string[] names = name.Split(' ');
            string firstName = names.First();
            string lastName = names.Last();
            int unlocked = 0;

            List<LockedUser> user = AdminUserDataLayer.GetLockedUsers();

            foreach (LockedUser lockedUser in user)
            {
                if (lockedUser.FirstName == firstName && lockedUser.LastName == lastName)
                {
                    if (lockedUser.Role == "coach")
                    {
                        unlocked = AdminUserDataLayer.EnableUserAccount(firstName, lastName);
                    }
                    else
                    {
                        Label1.Text = "If you are a manager you will need to contact the IT Department to unlock your account";
                    }
                }
            }

            if (unlocked > 0)
                Label1.Text = "Account unlocked";
        }
    }
}